// frontend/react/src/Counter.tsx
import { useEffect, useState } from "react";
import { AppDocumentHandle } from "./automerge";

export default function Counter({ handle }: { handle: AppDocumentHandle }) {
  const [counter, setCounter] = useState(0)

  useEffect(() => {
    handle.on("change", ({ doc }) => {
      setCounter(doc.counter || 0)
    })
  }, [handle])

  const incrementCounter = () => {
    handle.change((doc) => {
      doc.counter = (doc.counter || 0) + 1
    })
  }

  return <div className="card bg-base-300 mx-auto rounded-4xl">
    <div className="card-body">
      <h2 className="text-2xl">Community Counter</h2>
      <p className="text-sm">Number of times clicked by everybody</p>
      <strong className="text-3xl pt-2 pb-3">{counter}</strong>
      <button className="btn btn-primary" onClick={incrementCounter}>
        Increment
      </button>
    </div>
  </div>
}

// frontend/vue/src/Counter.vue
<script setup lang="ts">
import { ref, onMounted, defineProps } from 'vue'
import type { AppDocumentHandle } from './automerge.js'

// Define props for the component
const props = defineProps<{
  handle: AppDocumentHandle
}>()

// Initialize counter state
const counter = ref<number>(0)

// Set up listener for document changes
onMounted(() => {
  props.handle.on('change', ({ doc }: { doc: { counter?: number } }) => {
    counter.value = doc.counter || 0
  })
})

// Function to increment the counter
function incrementCounter() {
  props.handle.change((doc: { counter?: number }) => {
    doc.counter = (doc.counter || 0) + 1
  })
}
</script>

<template>
  <div class="card bg-base-300 mx-auto rounded-4xl">
    <div class="card-body">
      <h2 class="text-2xl">Community Counter</h2>
      <p class="text-sm">Number of times clicked by everybody</p>
      <strong class="text-3xl pt-2 pb-3">{{ counter }}</strong>
      <button class="btn btn-primary" @click="incrementCounter">Increment</button>
    </div>
  </div>
</template>
